# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Matt Hall
tagline:          'A Jekyll theme'
description:      Designer & developer. Student at <a href="https://osu.edu">OSU</a>. Built <a href="https://github.com/halltech/Beacon">Beacon</a> and <a href="https://github.com/mh15/unsure">Unsure</a>.
url:              https://mh15.github.io/matthall
baseurl:          /

author:
  name:           'Matt Hall'
  url:            https://twitter.com/matthew349hall

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/poole/hyde
  account:        https://github.com/mh15

repository: matthall/mh15.github.io


gems: [jekyll-paginate]